const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILURE = 'LOGIN_FAILURE';
const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';

export { LOGIN, LOGOUT, LOGIN_SUCCESS, LOGIN_FAILURE, DISPLAY_NOTIFICATION_DRAWER, HIDE_NOTIFICATION_DRAWER };